version: '3.9'

services:
  postgres:
    image: postgres:15-alpine
    container_name: venzory-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: venzory
      POSTGRES_PASSWORD: venzory
      POSTGRES_DB: venzory
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U venzory']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:

